version: "3"

vars:
  ALL: . tests/
  VENV: .venv/bin
  SOURCES: ./

tasks:
  lint-fix:
    desc: "Fix linting issues"
    cmds:
      - "{{.VENV}}/ruff check --fix {{.SOURCES}}"
      - "{{.VENV}}/ruff format {{.SOURCES}}"

  ruff:
    desc: "Run ruff"
    cmds:
      - "{{.VENV}}/ruff check {{.SOURCES}}"
      - "{{.VENV}}/ruff format {{.SOURCES}}"

  # Task to open the latest coverage report in a web browser
  coverage:
    desc: "Open the latest coverage report in a web browser"
    cmds:
      - open tests/coverage/index.html

  # Task to run all linting tasks (isort, mypy)
  lint:
    desc: "Run all linting tasks"
    deps:
      - ruff
      - mypy

  # Task to run MyPy for static type checking on the source code
  mypy:
    desc: "Run MyPy for static type checking"
    cmds:
      - "{{.VENV}}/mypy --ignore-missing-imports {{.SOURCES}}"

  # Task to run linting and tests
  qa:
    desc: "Run linting and tests"
    deps:
      - test
      - lint

  # Task to run tests using pytest with coverage reporting
  test:
    desc: "Run tests with coverage"
    cmds:
      - pytest -vv --cov --cov-report=html:tests/coverage --cov-fail-under=95 $(if [ -n "{{.CLI_ARGS}}" ]; then echo "{{.CLI_ARGS}}"; else echo .; fi)
